name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün gece yarısı çalıştırır

  workflow_dispatch:  # Manuel çalıştırmaya izin verir

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # v3 yerine v4 kullanıldı

      - name: Ensure output directory exists
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload Snake SVG Artifact
        uses: actions/upload-artifact@v4  # v3 yerine v4 kullanıldı
        with:
          name: snake
         
